version: "3.0"
  
services:
  getstickerset:
    image: getstickerset
    build:
      context: .
    logging:
      driver: json-file
      options:
        max-file: "5"
        max-size: 10m
    container_name: getstickerset
    command: --token=<Telegram bot token>
